# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a990835fd204223eb640f55f1a3a4124f276e32c979607d205e9fdf09a3d942ccb4005bc1a1846473f75914f0b15b03c6c810e0786bb9b5ba8fca4e5b7a9242

test:
  secret_key_base: 570c4200e10cc3c0775a2c525b400ad3ea659cf5a3f8c5c65d2d0806ee157834f0901536579344d8705c12aff391b0e2943c69050ebc2f2a848227cd1d667a89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
